# This file was generated by GoReleaser. DO NOT EDIT.
cask "husage" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/husage"]
    end
  end

  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "39bbbb34c2bb98a95184e71758041060c4a5df6e22cb483ddd25e3a7862bc246"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d0f82a2ec0350c025a887859a7b1d622609d76fc5093d3f222317a86b324c29"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83c84840b610cb1140d90fd36aac9ac286edb13db7356669337f47442e91607e"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb86a8b405228f115a9332d869ef0f89a16f7d93e821e15cd47597afc1ad80a3"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "husage"
  desc "Terminal dashboard for coding subscription usage"
  homepage "https://github.com/franciscocpg/husage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "husage"

  # No zap stanza required

  caveats <<~EOS
    Install the native Claude, Codex, or Cursor CLI for the accounts you want to monitor.
  EOS
end
