# This file was generated by GoReleaser. DO NOT EDIT.
cask "husage" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "439ee2f28f57096041c590dda4d19b5a594cf0debbb2c3fc677bd6a1115fe42b"
      url "https://github.com/franciscocpg/husage/releases/download/v0.1.0/husage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36dd81e63e26bbd755a6215af4f062bb7bf55311b98cac6b03a11bd2d8b0ea9a"
      url "https://github.com/franciscocpg/husage/releases/download/v0.1.0/husage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "253c43379a983fdc12f03e23a5333db56bf7cba1c493f11e9bb299aa7173df84"
      url "https://github.com/franciscocpg/husage/releases/download/v0.1.0/husage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c15d1c6b010a4909612db611162d9021801a44d48d0b58dca8872e19385571f"
      url "https://github.com/franciscocpg/husage/releases/download/v0.1.0/husage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "husage"
  desc "Terminal dashboard for coding subscription usage"
  homepage "https://github.com/franciscocpg/husage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "husage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/husage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Install the native Claude, Codex, or Cursor CLI for the accounts you want to monitor.
  EOS
end
