# This file was generated by GoReleaser. DO NOT EDIT.
cask "husage" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/husage"]
    end
  end

  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "d960036a7ccd411b3cf005a37bbb08aa22952493a4a112670fcb677455191ef6"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f4f4573249695448890348aed4ace054726e921fd4321434f87af2ae26f1f77"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "667dc4844d2ce30143eb8e044e369d1863a35b8628108f395f813af580cd80a3"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7298f1f48015c7fca633e4458cdde117fc9b1af73ee735e0f2b7239c673c5520"
      url "https://github.com/franciscocpg/husage/releases/download/v#{version}/husage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "husage"
  desc "Terminal dashboard for coding subscription usage"
  homepage "https://github.com/franciscocpg/husage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "husage"

  # No zap stanza required

  caveats <<~EOS
    Install the native Claude, Codex, or Cursor CLI for the accounts you want to monitor.
  EOS
end
